package com.myspace.dmnexample1;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Agreement implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String agreementType;
	private java.lang.String agreementGroupType;

	public Agreement() {
	}

	public java.lang.String getAgreementType() {
		return this.agreementType;
	}

	public void setAgreementType(java.lang.String agreementType) {
		this.agreementType = agreementType;
	}

	public java.lang.String getAgreementGroupType() {
		return this.agreementGroupType;
	}

	public void setAgreementGroupType(java.lang.String agreementGroupType) {
		this.agreementGroupType = agreementGroupType;
	}

	public Agreement(java.lang.String agreementType,
			java.lang.String agreementGroupType) {
		this.agreementType = agreementType;
		this.agreementGroupType = agreementGroupType;
	}

}